name: Test and Merge Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  test_and_merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.3' 

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Auto Merge
        uses: pascalgn/automerge-action@v0.14.3
        with:
          MERGE_LABELS: ""
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
